// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0lqWqLeERILDXa1Zw4qnswaIgv6PLAf0',
    appId: '1:1008600573757:web:50cd486c939d49d1700754',
    messagingSenderId: '1008600573757',
    projectId: 'ontestapps-612ca',
    authDomain: 'ontestapps-612ca.firebaseapp.com',
    storageBucket: 'ontestapps-612ca.firebasestorage.app',
    measurementId: 'G-EH1LQF6ZV3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOyh_08iibeoP-RJ-QjG141fZfNcz34IY',
    appId: '1:1008600573757:android:938afe38df475586700754',
    messagingSenderId: '1008600573757',
    projectId: 'ontestapps-612ca',
    storageBucket: 'ontestapps-612ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKp1uZbiz2SLntOlbFY0OS6Hm_EocH4lw',
    appId: '1:1008600573757:ios:2865d27f62590aed700754',
    messagingSenderId: '1008600573757',
    projectId: 'ontestapps-612ca',
    storageBucket: 'ontestapps-612ca.firebasestorage.app',
    iosBundleId: 'com.leloeduk.ontestapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKp1uZbiz2SLntOlbFY0OS6Hm_EocH4lw',
    appId: '1:1008600573757:ios:2865d27f62590aed700754',
    messagingSenderId: '1008600573757',
    projectId: 'ontestapps-612ca',
    storageBucket: 'ontestapps-612ca.firebasestorage.app',
    iosBundleId: 'com.leloeduk.ontestapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0lqWqLeERILDXa1Zw4qnswaIgv6PLAf0',
    appId: '1:1008600573757:web:8f79ef3e7510cbd9700754',
    messagingSenderId: '1008600573757',
    projectId: 'ontestapps-612ca',
    authDomain: 'ontestapps-612ca.firebaseapp.com',
    storageBucket: 'ontestapps-612ca.firebasestorage.app',
    measurementId: 'G-KJ0YXTYWPG',
  );
}
